
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IngeDolan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MILESTONE
{

    public string MILESTONE_ID { get; set; }

    public string TASK_ID { get; set; }

    public string STORY_ID { get; set; }

    public string BACKLOG_ID { get; set; }

    public string PROJECT_ID { get; set; }

    public Nullable<int> PROGRESS { get; set; }

    public Nullable<System.DateTime> DATES { get; set; }



    public virtual TASK TASK { get; set; }

}

}
