
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IngeDolan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class persona
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public persona()
    {

        this.telefonoes = new HashSet<telefono>();

        this.telefonoes1 = new HashSet<telefono>();

    }


    public string nombre { get; set; }

    public string apellido1 { get; set; }

    public string apellido2 { get; set; }

    public string cedula { get; set; }

    public string carne { get; set; }

    public bool sexo { get; set; }

    public System.DateTime fechaNac { get; set; }

    public string email { get; set; }

    public string id { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<telefono> telefonoes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<telefono> telefonoes1 { get; set; }

}

}
